### ISSUE TITLE
LexingError: unexpected character

### ISSUE THREAD

**Issue by AllanOricil** [paustint/soql-parser-js#140]
- [ ] Feature
- [X ] Bug

## Description
Cant parse the following query. I also added a print screen of the console debug log showing the exception and the query input I pass to the parser.

````js
LexingError: unexpected character: ->​<- at offset: 1124, skipped 1 characters. (71:40)
    at new LexingError (http://localhost:3000/_nuxt/app.js:520527:28)
    at parse (http://localhost:3000/_nuxt/app.js:521074:15)
    at parseQuery (http://localhost:3000/_nuxt/app.js:521861:84)
    at VueComponent.onClickExecuteQueryButton (http://localhost:3000/_nuxt/app.js:235979:95)
    at click (http://localhost:3000/_nuxt/app.js:525224:39)
    at invokeWithErrorHandling (http://localhost:3000/_nuxt/app.js:546467:26)
    at HTMLButtonElement.invoker (http://localhost:3000/_nuxt/app.js:546792:14)
    at HTMLButtonElement.original._wrapper (http://localhost:3000/_nuxt/app.js:551521:25)
````

````js
SELECT
  AccountNumber,
  AccountSource,
  Active__c,
  AnnualRevenue,
  BillingAddress,
  BillingCity,
  BillingCountry,
  BillingGeocodeAccuracy,
  BillingLatitude,
  BillingLongitude,
  BillingPostalCode,
  BillingState,
  BillingStreet,
  CleanStatus,
  CreatedById,
  CreatedDate,
  CustomerPriority__c,
  DandbCompanyId,
  Description,
  DunsNumber,
  Fax,
  Id,
  Industry,
  IsDeleted,
  Jigsaw,
  JigsawCompanyId,
  LastActivityDate,
  LastModifiedById,
  LastModifiedDate,
  LastReferencedDate,
  LastViewedDate,
  MasterRecordId,
  NaicsCode,
  NaicsDesc,
  Name,
  NumberOfEmployees,
  NumberofLocations__c,
  OwnerId,
  Ownership,
  ParentId,
  Phone,
  PhotoUrl,
  Rating,
  ShippingAddress,
  ShippingCity,
  ShippingCountry,
  ShippingGeocodeAccuracy,
  ShippingLatitude,
  ShippingLongitude,
  ShippingPostalCode,
  ShippingState,
  ShippingStreet,
  Sic,
  SicDesc,
  Site,
  SLA__c,
  SLAExpirationDate__c,
  SLASerialNumber__c,
  SystemModstamp,
  Test__c,
  TickerSymbol,
  Tradestyle,
  Type,
  UpsellOpportunity__c,
  Website,
  YearStarted
FROM
  Account
WHERE
  SLAExpirationDate__c = NEXT_N_FISCAL_​YEARS:10
````

![image](https://user-images.githubusercontent.com/55927613/110170358-025ae100-7df2-11eb-918e-2ab5e1ec2900.png)

**Comment by paustint** [comment]
@AllanOricil, I will take a look in the next few days. Can you confirm you are on version 3.x?

**Comment by AllanOricil** [comment]
@paustint Thank you. And I confirm I'm using v3.0.0

**Comment by AllanOricil** [comment]
@paustint I think I found why the above string is not being accepted. Man, there is a fucking hidden character that I can't remove, nor actually see which is the encoded value.

`````js
NEXT_N_FISCAL_​YEARS:10
````

The character is between `_` and `Y`. If you paste on vscode and then try to navigate between chars you will see that once you press left arrow it will stop in this invisible character

**Comment by AllanOricil** [comment]
In the console I can copy this invisible character 

![image](https://user-images.githubusercontent.com/55927613/110202675-35d55400-7e62-11eb-8519-c3bc1a0c19c4.png)

**Comment by AllanOricil** [comment]
wtf is this type of encoding!!! I know it is not related to your lib. But would you know what is it?

**Comment by AllanOricil** [comment]
I was finally able to remove that hidden character and now everything works as expected. The issue was not caused by the lib :)

"NEXT_N_FISCAL_​YEARS:10".replace(/\u200B|\u200b/, '') removes this weird encoded character
